import { RouteInfo } from './sidebar.metadata';

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    path: '/etudiants',
    title: 'Etudiant',
    icon: 'bx bx-cookie',
    class: 'sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/etudiants/list',
        title: 'List Etudiants',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '/Projet',
    title: 'Projet',
    icon: 'bx bx-cookie',
    class: 'sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/Projet/list',
        title: 'List Projet',
        icon: 'bx bx-list-ul',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/Projet/form',
        title: 'Add Projet',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '/equipes',
    title: 'Equipes',
    icon: 'bx bx-cookie',
    class: 'sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/equipes/dashboard',
        title: 'Dashboard',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/equipes/list',
        title: 'Liste Equipes',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/equipes/espace',
        title: 'Espace Equipe',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/equipes/admin',
        title: 'Admin',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
    ],
  },

  /*{
    path: '/univDepart',
    title: 'Uni & Dep',
    icon: 'bx bx-cookie',
    class: 'sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/univDepart/depart/home',
        title: 'Departements',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/univDepart/univ/home',
        title: 'Universites',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
    ],
  },

  { path: '/Entreprise', 
    title: 'Entreprise', 
    icon: 'bx bx-cookie', 
    class: 'sub', 
    badge: '', 
    badgeClass: '', 
    isExternalLink: false, 
    submenu: [
      { path: '/Entreprise/list', 
        title: 'List Entreprise', 
        icon: 'bx bx-right-arrow-alt', 
        class: '', 
        badge: '', 
        badgeClass: '', 
        isExternalLink: false, 
        submenu: [] 
      },
    ],
  },

  {
    path: 'javascript:;',
    title: 'Menu Levels',
    icon: 'bx bx-menu',
    class: 'sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: 'javascript:;',
        title: 'Level 1',
        icon: 'bx bx-right-arrow-alt',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: 'javascript:;',
        title: 'Level 1',
        icon: 'bx bx-right-arrow-alt',
        class: 'sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [
          {
            path: 'javascript:;',
            title: 'level 2',
            icon: 'bx bx-right-arrow-alt',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
          {
            path: 'javascript:;',
            title: 'level 2',
            icon: 'bx bx-right-arrow-alt',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
          },
        ],
      },
    ],
  },
  {
    path: 'https://codervent.com/bulona-angular/docs/',
    title: 'Documentation',
    icon: 'bx bx-folder',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: true,
    submenu: [],
  },
  {
    path: 'https://themeforest.net/user/codewrrap/portfolio',
    title: 'Support',
    icon: 'bx bx-support',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: true,
    submenu: [],
  },*/
];
